title: Notes de Langue
description: My notes in learning the French language
author: #
baseurl: /notes-de-langue

remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true

# Color scheme currently only supports "dark" or nil (default)
color_scheme: "dark"
